
services:
  postgres:
    image: postgres:15
    container_name: smartloan-postgres
    environment:
      POSTGRES_DB: smartloandb
      POSTGRES_USER: smartloan
      POSTGRES_PASSWORD: smartloan123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - smartloan-network

  app:
    build: .
    container_name: smartloan-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/smartloandb
      SPRING_DATASOURCE_USERNAME: smartloan
      SPRING_DATASOURCE_PASSWORD: smartloan123
      JAVA_TOOL_OPTIONS: -Duser.timezone=Asia/Kolkata
    depends_on:
      - postgres
    networks:
      - smartloan-network

volumes:
  postgres_data:

networks:
  smartloan-network:
    driver: bridge