apiVersion: v1
kind: ConfigMap
metadata:
  name: smartloan-config
data:
  POSTGRES_DB: smartloandb
  POSTGRES_USER: smartloan
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-service:5432/smartloandb
  SPRING_DATASOURCE_USERNAME: smartloan
  JAVA_TOOL_OPTIONS: -Duser.timezone=Asia/Kolkata