# Database Connection
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://127.0.0.1:5432/smartloandb?TimeZone=Asia%2FKolkata}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:smartloan}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:smartloan123}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# App Port
server.port=8080

# JWT
jwt.secret=smartloan-secret-key-for-jwt-token-generation-must-be-256-bits
jwt.expiration=86400000
logging.level.org.springframework.security=DEBUG

# Actuator
management.endpoint.health.probes.enabled=true
management.health.livenessState.enabled=true
management.health.readinessState.enabled=true
management.endpoints.web.exposure.include=health,info